# From this directory:
#   docker build -t jobber:latest-py36 -f Dockerfile_py36 --force-rm ..

FROM ubuntu

RUN apt-get update
RUN apt-get install -y python3.6
RUN ln /usr/bin/python3.6 /usr/bin/python
# RUN curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
# RUN python /tmp/get-pip.py

# Add other default packages here
RUN apt-get install -y python3-pip git

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /jobber
COPY setup.py .
COPY src /jobber/src/
RUN pip3 install .